server.port=11000

# DB Information
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://mariadb-recovery.crw06g6ga7s0.ap-northeast-2.rds.amazonaws.com:3306/myDB?sslMode=trust


# DB's ID
spring.datasource.username=${DB_USERNAME}

# DB's Password
spring.datasource.password=${DB_PASSWORD}

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.servlet.session.tracking-modes=cookie
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
# Thymeleaf
spring.thymeleaf.cache=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# RedisDB Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}

# Redis Session
spring.session.store-type=redis
spring.session.redis.namespace=spring:session

# MongoDB Connection
spring.data.mongodb.host=3.36.242.179
spring.data.mongodb.port=27017
spring.data.mongodb.database=MyDB
spring.data.mongodb.username=${MONGO_USERNAME}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.authentication-database=admin

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@3.36.242.179:27017/MyDB?authSource=admin

# Mail
spring.mail.host=smtp.naver.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com


#weather API
weather.api.key=${WEATHER_API_KEY}

# Aladin API
aladin.api.key=${ALADIN_API_KEY}

#library API
library.api.key=${LIBRARY_API_KEY}
library.api.base-url=https://data4library.kr/api

# Claude (Anthropic) API
anthropic.api-key=${ANTHROPIC_API_KEY}
anthropic.model=claude-haiku-4-5-20251001
anthropic.url=https://api.anthropic.com/v1/messages

# Gemini API
gemini.api-key=${GEMINI_API_KEY}
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent

# OpenAI API
openai.api.key=${OPENAI_API_KEY}



# AWS S3
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.s3.bucket-name=imagemake-bucket
aws.s3.region=ap-southeast-2

# MyBatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.from.domain
mybatis.configuration.map-underscore-to-camel-case=true


# Kakao
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.redirect-uri=http://localhost:8080/user/kakao/callback